server:
  port: 9000
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///E:/Poli2023-2/PDS/Repos/Done/3.SpringCloudConfig
  security:
    user:
      name: ${CONFIG_NAME}
      password: ${CONFIG_PASSWORD}

